FROM golang:1.20-alpine as builder

WORKDIR /app

RUN go mod download
COPY hoover/ ./
RUN go mod tidy
RUN go build -o main .

FROM ubuntu
RUN apt update
ARG DEBIAN_FRONTEND=noninteractive
RUN apt install -y awscli inotify-tools unzip curl ca-certificates openjdk-11-jdk
COPY --from=builder /app/main /
RUN chmod 755 /main

RUN mkdir -p /heapdumps
RUN chmod 777 /heapdumps
CMD ["/main", "-analyse=true", "/var/tmp/heapdumps"]

